export const metadata = {
  title: 'Terms of Service — ChartAI',
};

export default function Terms() {
  return (
    <div style={s.page}>
      <div style={s.container}>
        <a href="/" style={s.back}>← Back to ChartAI</a>
        <h1 style={s.h1}>Terms of Service</h1>
        <p style={s.updated}>Last updated: March 2025</p>

        <Section title="1. Service Description">
          ChartAI provides AI-powered technical analysis of cryptocurrency chart images. You upload a chart screenshot and receive an automated prediction generated by Claude AI (Anthropic). The service is offered on a freemium basis: a limited number of analyses are free, with additional analyses available for a one-time fee per analysis.
        </Section>

        <Section title="2. Not Financial Advice">
          All analysis provided by ChartAI is for <strong>educational and informational purposes only</strong>. Nothing on this platform constitutes financial, investment, or trading advice. You should not make any financial decisions based solely on output from this service. Always do your own research and consult a qualified financial advisor before making investment decisions. You use this service entirely at your own risk.
        </Section>

        <Section title="3. Payments">
          Paid analyses are processed securely through PayPal. Each payment covers a single analysis. Payments are <strong>non-refundable</strong> except in the event of a technical failure where an analysis could not be delivered after payment was captured — in which case you may contact us for a refund with your transaction ID.
        </Section>

        <Section title="4. Free Tier">
          Each user receives a limited number of free analyses. Free uses are tracked per browser session and IP address. Attempting to circumvent free-tier limits (e.g., clearing browser storage, using automated tools) is a violation of these terms and may result in access being restricted.
        </Section>

        <Section title="5. Acceptable Use">
          You agree not to:
          <ul style={s.list}>
            <li>Use the service for automated scraping or bulk analysis</li>
            <li>Attempt to reverse engineer, abuse, or overload the service</li>
            <li>Upload content that is not a cryptocurrency or financial chart</li>
            <li>Use the service in any way that violates applicable laws</li>
          </ul>
        </Section>

        <Section title="6. Limitation of Liability">
          ChartAI and its operators are not liable for any financial losses, damages, or decisions made based on the analysis provided. The service is provided "as is" without warranties of any kind. Accuracy of AI predictions is not guaranteed.
        </Section>

        <Section title="7. Changes to Terms">
          We reserve the right to update these terms at any time. Continued use of the service after changes constitutes acceptance of the updated terms.
        </Section>

        <Section title="8. Contact">
          For support or refund requests, contact us at: <strong>support@chartai.pro</strong>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div style={s.section}>
      <h2 style={s.h2}>{title}</h2>
      <p style={s.body}>{children}</p>
    </div>
  );
}

const s = {
  page:      { minHeight: '100vh', background: 'var(--bg)', color: 'var(--text)', padding: '40px 20px 80px', fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" },
  container: { maxWidth: 700, margin: '0 auto' },
  back:      { display: 'inline-block', fontSize: 13, color: 'var(--muted)', textDecoration: 'none', marginBottom: 32 },
  h1:        { fontSize: 28, fontWeight: 700, marginBottom: 6 },
  updated:   { fontSize: 13, color: 'var(--muted)', marginBottom: 40 },
  section:   { marginBottom: 32, padding: 24, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 14 },
  h2:        { fontSize: 16, fontWeight: 600, marginBottom: 10, color: 'var(--accent)' },
  body:      { fontSize: 14, lineHeight: 1.7, color: 'var(--text)', opacity: .85 },
  list:      { paddingLeft: 20, marginTop: 8, display: 'flex', flexDirection: 'column', gap: 4 },
};
